[client]
showErrorDetails = true

[logger]
level = "debug"

[theme]
primaryColor = "#0F3460"
backgroundColor = "#F4F6FB"
secondaryBackgroundColor = "#ffffff"
textColor = "#1A1A2E"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
headless = true
